export const localProfiles = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    auth_user_id: null,
    role: "creator",
    display_name: "Maya Alvarez",
    handle: "@mayaonfilm",
    bio: "Thrift finds, art walks, and honest recommendations for people who spend their weekends around Bisbee.",
    city: "Bisbee, AZ",
    categories: ["Instagram", "Vintage", "Local"],
    followers: 4200,
    avg_views: 1900,
    audience_age: "68% ages 18-34",
    website: "",
    avatar_url: "/photos/market-creator.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    auth_user_id: null,
    role: "creator",
    display_name: "Drew Kim",
    handle: "@drew.eats",
    bio: "No-frills food reviews and weekly West Texas roundups for people deciding what is worth the drive.",
    city: "Marfa, TX",
    categories: ["TikTok", "Food", "Local"],
    followers: 3800,
    avg_views: 4100,
    audience_age: "61% ages 21-39",
    website: "",
    avatar_url: "/photos/drew-kitchen.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    auth_user_id: null,
    role: "space_owner",
    display_name: "Jay Morrison",
    handle: "Silver 84 Volvo",
    bio: "A restored wagon parked near the farmers market and driven through town on weekday delivery routes.",
    city: "Livingston, MT",
    categories: ["Vehicle", "Physical", "Local"],
    followers: 0,
    avg_views: 8400,
    audience_age: "Locals + Yellowstone traffic",
    website: "",
    avatar_url: "/photos/jay-volvo.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    auth_user_id: null,
    role: "space_owner",
    display_name: "Athens Corner Co-op",
    handle: "Cafe + community window",
    bio: "A cafe window, sidewalk sign, and counter card spot on the walk between campus and Court Street.",
    city: "Athens, OH",
    categories: ["Cafe", "Storefront", "Students"],
    followers: 0,
    avg_views: 6200,
    audience_age: "76% ages 18-29",
    website: "",
    avatar_url: "/photos/small-town-coffee.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    auth_user_id: null,
    role: "business",
    display_name: "Driftless Coffee Roasters",
    handle: "@driftlesscoffee",
    bio: "A small-town roaster looking for affordable local launch partners, window space, and community voices.",
    city: "Decorah, IA",
    categories: ["Coffee", "Local", "Launch"],
    followers: 2100,
    avg_views: 1300,
    audience_age: "College, families, weekend visitors",
    website: "driftless.example",
    avatar_url: "/photos/small-town-coffee.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "66666666-6666-4666-8666-666666666666",
    auth_user_id: null,
    role: "business",
    display_name: "Greenbrier Print House",
    handle: "@greenbrierprints",
    bio: "Independent prints, trail maps, and postcards made for small shops across the Alleghenies.",
    city: "Thomas, WV",
    categories: ["Art", "Main Street", "Product"],
    followers: 2900,
    avg_views: 1700,
    audience_age: "Locals, hikers, weekend visitors",
    website: "greenbrier.example",
    avatar_url: "/photos/rural-main-street.jpg",
    verified: false,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "77777777-7777-4777-8777-777777777777",
    auth_user_id: null,
    role: "space_owner",
    display_name: "Redwood Produce Stand",
    handle: "Highway 201 farm stand",
    bio: "A family produce stand with bright roadside visibility during the Central Valley growing season.",
    city: "Dinuba, CA",
    categories: ["Farm stand", "Roadside", "Food"],
    followers: 0,
    avg_views: 3600,
    audience_age: "Families + farm traffic",
    website: "",
    avatar_url: "/photos/roadside-farm-stand.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "88888888-8888-4888-8888-888888888888",
    auth_user_id: null,
    role: "space_owner",
    display_name: "Waller's Market",
    handle: "Main Street grocery",
    bio: "A rural market with two front windows, a checkout counter, and a loyal weekly customer base.",
    city: "Mercer, WI",
    categories: ["Market", "Storefront", "Community"],
    followers: 0,
    avg_views: 2200,
    audience_age: "Year-round locals + lake visitors",
    website: "",
    avatar_url: "/photos/rural-market.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "99999999-9999-4999-8999-999999999999",
    auth_user_id: null,
    role: "space_owner",
    display_name: "Maple Street Barber",
    handle: "Two-chair neighborhood shop",
    bio: "A classic barbershop with a waiting bench, mirror cards, and steady small-town conversation.",
    city: "Lanesboro, MN",
    categories: ["Barber", "Counter", "Community"],
    followers: 0,
    avg_views: 900,
    audience_age: "Adults 25-64 + families",
    website: "",
    avatar_url: "/photos/small-town-barber.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    auth_user_id: null,
    role: "space_owner",
    display_name: "Little River Bakery",
    handle: "Main Street bake shop",
    bio: "A sunny bakery window and pickup counter serving commuters, families, and Saturday visitors.",
    city: "Abingdon, VA",
    categories: ["Bakery", "Window", "Food"],
    followers: 0,
    avg_views: 1800,
    audience_age: "Families + downtown foot traffic",
    website: "",
    avatar_url: "/photos/small-town-bakery.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    auth_user_id: null,
    role: "creator",
    display_name: "Main Street Makers",
    handle: "@mainstreetmakers",
    bio: "A weekly email and social roundup featuring makers, shops, and events across North Georgia towns.",
    city: "Dahlonega, GA",
    categories: ["Newsletter", "Instagram", "Makers"],
    followers: 3600,
    avg_views: 2400,
    audience_age: "Local shoppers ages 25-54",
    website: "mainstreetmakers.example",
    avatar_url: "/photos/rural-main-street.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    auth_user_id: null,
    role: "business",
    display_name: "Cedar Coffee House",
    handle: "@cedarcoffeehouse",
    bio: "A porch-front coffee shop testing low-cost partnerships with nearby makers, guides, and events.",
    city: "Eureka Springs, AR",
    categories: ["Coffee", "Tourism", "Community"],
    followers: 1700,
    avg_views: 1100,
    audience_age: "Locals + weekend travelers",
    website: "cedarcoffee.example",
    avatar_url: "/photos/small-town-coffee.jpg",
    verified: true,
    is_demo: true,
    onboarding_complete: true,
  },
];

export const localListingSeeds = [
  {
    id: "a1111111-1111-4111-8111-111111111111",
    owner_profile_id: localProfiles[0].id,
    title: "Local story + saved highlight",
    channel: "Instagram",
    format: "3 frames - 48 hr highlight",
    price: 18,
    price_unit: "story set",
    description: "A natural three-frame recommendation for a local shop, event, or service, saved for 48 hours.",
    demographics: "68% ages 18-34 - Bisbee area",
    image_url: "/photos/market-creator.jpg",
    status: "active",
  },
  {
    id: "a2222222-2222-4222-8222-222222222222",
    owner_profile_id: localProfiles[1].id,
    title: "West Texas food stop feature",
    channel: "TikTok",
    format: "30-45 sec - town tag included",
    price: 28,
    price_unit: "video",
    description: "One useful food or roadside-stop feature filmed on location and posted when local viewers are active.",
    demographics: "61% ages 21-39 - West Texas",
    image_url: "/photos/drew-kitchen.jpg",
    status: "active",
  },
  {
    id: "a3333333-3333-4333-8333-333333333333",
    owner_profile_id: localProfiles[2].id,
    title: "Rear-window local route",
    channel: "Vehicle",
    format: "18 x 24 in - weather-safe",
    price: 5,
    price_unit: "day",
    description: "Rear-window placement on a vintage wagon moving between downtown, the market, and local deliveries.",
    demographics: "8.4K monthly looks - local route",
    image_url: "/photos/jay-volvo.jpg",
    status: "active",
  },
  {
    id: "a4444444-4444-4444-8444-444444444444",
    owner_profile_id: localProfiles[3].id,
    title: "Cafe window + sidewalk sign",
    channel: "Cafe window",
    format: "2 small placements - weekly proof",
    price: 15,
    price_unit: "week",
    description: "A letter-size window poster plus a small sidewalk-sign panel between campus and downtown.",
    demographics: "6.2K weekly looks - 76% ages 18-29",
    image_url: "/photos/small-town-coffee.jpg",
    status: "active",
  },
  {
    id: "a5555555-5555-4555-8555-555555555555",
    owner_profile_id: localProfiles[4].id,
    title: "Local coffee launch partners",
    channel: "Business brief",
    format: "Story - tasting - counter card",
    price: 35,
    price_unit: "partner",
    description: "A small paid brief for creators and counter spaces with a real connection to Driftless-area coffee culture.",
    demographics: "College, families, and weekend visitors",
    image_url: "/photos/small-town-coffee.jpg",
    status: "active",
  },
  {
    id: "a6666666-6666-4666-8666-666666666666",
    owner_profile_id: localProfiles[5].id,
    title: "Main Street postcard swap",
    channel: "Main Street",
    format: "50 cards - 3 local counters",
    price: 24,
    price_unit: "run",
    description: "A tiny cross-promotion placing your card beside our trail maps and art prints in three nearby shops.",
    demographics: "Locals, hikers, and weekend visitors",
    image_url: "/photos/rural-main-street.jpg",
    status: "active",
  },
  {
    id: "a7777777-7777-4777-8777-777777777777",
    owner_profile_id: localProfiles[6].id,
    title: "Farm-stand umbrella panel",
    channel: "Farm stand",
    format: "One 12 x 18 in panel",
    price: 2,
    price_unit: "day",
    description: "A weather-safe sign beside the produce table where drivers already slow down and pull over.",
    demographics: "3.6K monthly stops - families",
    image_url: "/photos/roadside-farm-stand.jpg",
    status: "active",
  },
  {
    id: "a8888888-8888-4888-8888-888888888888",
    owner_profile_id: localProfiles[7].id,
    title: "Checkout counter card",
    channel: "Storefront",
    format: "5 x 7 in card - front counter",
    price: 4,
    price_unit: "week",
    description: "A simple counter card seen by regular grocery shoppers and lake visitors while they check out.",
    demographics: "2.2K weekly shoppers - all ages",
    image_url: "/photos/rural-market.jpg",
    status: "active",
  },
  {
    id: "a9999999-9999-4999-8999-999999999999",
    owner_profile_id: localProfiles[8].id,
    title: "Waiting-bench card holder",
    channel: "Counter card",
    format: "A6 card - mirror + waiting bench",
    price: 3,
    price_unit: "week",
    description: "A small card holder where customers have time to read about a nearby service or event.",
    demographics: "900 monthly visits - local households",
    image_url: "/photos/small-town-barber.jpg",
    status: "active",
  },
  {
    id: "b1111111-1111-4111-8111-111111111111",
    owner_profile_id: localProfiles[9].id,
    title: "Bakery pickup-window card",
    channel: "Bakery window",
    format: "Letter-size poster - pickup window",
    price: 6,
    price_unit: "week",
    description: "A clean poster beside the pastry case for a local event, class, maker, or family-friendly service.",
    demographics: "1.8K weekly visits - families",
    image_url: "/photos/small-town-bakery.jpg",
    status: "active",
  },
  {
    id: "b2222222-2222-4222-8222-222222222222",
    owner_profile_id: localProfiles[10].id,
    title: "Weekly local-maker mention",
    channel: "Newsletter",
    format: "One feature - email + Instagram",
    price: 16,
    price_unit: "mention",
    description: "A concise recommendation in our Friday local-maker roundup with a photo, link, and town tag.",
    demographics: "2.4K local readers - ages 25-54",
    image_url: "/photos/rural-main-street.jpg",
    status: "active",
  },
  {
    id: "b3333333-3333-4333-8333-333333333333",
    owner_profile_id: localProfiles[11].id,
    title: "Porch board + receipt footer",
    channel: "Community board",
    format: "2 small placements - 2 weeks",
    price: 30,
    price_unit: "partner",
    description: "A porch notice-board spot plus a short receipt message for a nearby event, maker, or guide.",
    demographics: "Locals + weekend travelers",
    image_url: "/photos/small-town-coffee.jpg",
    status: "active",
  },
];
